version: '3.8'

services:
  backend:
    build: ./backend
    image: ghcr.io/patiphatrattanosot/visit-home-backend
    container_name: backend_service
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "3000:3000"
    # env_file:
    #   - ./backend/.env
    restart: always
    networks:
      - app_network

  frontend:
    build: ./frontend
    image: ghcr.io/patiphatrattanosot/visit-home-frontend
    container_name: frontend_service
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "5173:5173"
    # env_file:
    #   - ./frontend/.env
    depends_on:
      - backend
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge