name: "build and deploy docker image"

on:
  push:
    tags:
      - "*" # Trigger เมื่อ push tag ใด ๆ

jobs:
  release-docker-image-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Verify extracted tag
        run: echo "Using TAG_NAME=${{ env.TAG_NAME }}"

      - name: Build and push Docker image using Docker Compose
        env:
          TAG_NAME: ${{ env.TAG_NAME }}
        run: |
          docker-compose build
          docker tag visit-home-frontend ghcr.io/patiphatrattanosoth/visit-home-frontend:${{ env.TAG_NAME }}
          docker tag visit-home-backend ghcr.io/patiphatrattanosoth/visit-home-backend:${{ env.TAG_NAME }}
          docker push ghcr.io/patiphatrattanosoth/visit-home-frontend:${{ env.TAG_NAME }}
          docker push ghcr.io/patiphatrattanosoth/visit-home-backend:${{ env.TAG_NAME }}
