name: "build and deploy docker image"

on:
  push:
    tags:
      - "*" # Trigger เมื่อ push tag ใด ๆ

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set TAG_NAME from Git tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Docker Compose Build
        run: docker-compose build
        env:
          TAG_NAME: ${{ env.TAG_NAME }}

      - name: Push Docker images to GHCR
        run: |
          docker push ghcr.io/patiphatrattanosot/visit-home-frontend:${{ env.TAG_NAME }}
          docker push ghcr.io/patiphatrattanosot/visit-home-backend:${{ env.TAG_NAME }}


      # # 4. Execute tests inside running container
      # - name: Execute tests in the running services
      #   run: docker compose exec test-app pytest
